blank_issues_enabled: false
- name: "Bug Report"
  description: "Report a bug in the system."
  title: "[Bug]: "
  labels: ["bug"]
  body: "./ISSUE_TEMPLATE/bug_report.md"
- name: "General"
  description: "Provide general feedback or inquiries."
  title: "[General]: "
  labels: ["general"]
  body: "./ISSUE_TEMPLATE/general.md"