name: Poke Actions
on:
  issues:
    types: [opened, closed]
  pull_request:
    types: [opened, closed]

jobs:
  pokemon:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write
    steps:
      - uses: DanielYuki/poke-actions@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}